baseURL = 'https://nineanswerer.github.io/'
languageCode = 'en-us'
title = '我的个人博客'
theme = 'PaperMod'

[params.homeInfoParams]
    Title = "你好，我是 NineAnswerer 👋"
    Content = "这是我的个人博客。我关注大数据、AI 和机器人。欢迎交流！"
        imageUrl = "avatar.png"
[[params.socialIcons]]
    name = "github"
    url = "https://github.com/nineanswerer"

[[params.socialIcons]]
    name = "email"
    url = "mailto:abcv@123456+789"

[[menu.main]]
    name = "关于"
    url = "/about"
    weight = 20

[[menu.main]]
    name = "存档"
    url = "/archives"
    weight = 10

[params]
    ShowToc = true          # 自动显示目录
    TocOpen = true         # 默认展开目录
    ShowReadingTime = true # 显示阅读时间
    ShowPostNavLinks = true # 显示上一篇/下一篇文章

[outputs]
    home = ["HTML", "RSS", "JSON"] # 必须添加 JSON 以便搜索插件读取数据

[[menu.main]]
    name = "搜索"
    url = "/search"
    weight = 5